name: tf2
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy=1.20.2
  - pandas=1.2.4
  - jupyter=1.0.0
  - scikit-image=0.18.1
  - scikit-learn=0.24.2
  - tensorflow-gpu=2.4.1
  - tensorflow-estimator=2.4.1
  - pip=21.1.2
  - pip:
    - opencv-python==3.4.2.17
