name: tf2
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy=1.16.4
  - pandas=0.24.2
  - jupyter=1.0.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - tensorflow-gpu=2.0.0
  - pip=19.1.1
  - pip:
    - opencv-python==3.4.2.17
